version: '2'
services:
  web:
    volumes:
      - ./:/app
      - /Users/cameronfranz/NoSync/glove.6B:/app/data2
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=8080
